# Generated by Django 4.1 on 2022-09-18 23:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mywatchlist', '0002_alter_mywatchlist_relase_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mywatchlist',
            old_name='relase_date',
            new_name='release_date',
        ),
    ]
